name: Continuous Integration

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

env:
  SETUP_NODE_VERSION: '24.x'
  SETUP_OKAPI_VERSION: '1.47.0'

jobs:
  test-action-ubuntu:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ env.SETUP_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install npm packages
        run: npm ci

      - name: Test setup-okapi-framework
        id: test-action-latest
        uses: ./
        with:
          version: ${{ env.SETUP_OKAPI_VERSION }}

      - name: Print output
        run: |
          echo "Installed Okapi to ${{ steps.test-action-latest.outputs.path }}"

      - name: Check Java version
        run: |
          echo "JAVA_HOME is set to: $JAVA_HOME"
          java -version

      - name: Run Tikal
        run: |
          tikal.sh -i

  test-action-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ env.SETUP_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install npm packages
        run: npm ci

      - name: Test setup-okapi-framework
        id: test-action-latest
        uses: ./
        with:
          version: ${{ env.SETUP_OKAPI_VERSION }}

      - name: Print output
        run: |
          echo "Installed Okapi to ${{ steps.test-action-latest.outputs.path }}"

      - name: Setup Java 11
        # windows-2022 uses Java 8 as the default, and Okapi requires Java 11
        # Using `echo "JAVA_HOME=$Env:JAVA_HOME_11_X64" >> $Env:GITHUB_ENV` will not work
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Check Java version
        run: |
          echo "JAVA_HOME is set to: $Env:JAVA_HOME"
          java -version

      - name: Run Tikal
        run: |
          tikal.bat -i
